Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150
  Include:
    - 'spec/**/*'

# Because of the way that blocks are used in RSpecs can end up being long when
# example groups are nested or many examples are checked.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
