require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150
  Include:
    - 'spec/**/*'

RSpec/EmptyExampleGroup:
  Enabled: false

# Because of the way that blocks are used in RSpecs can end up being long when
# example groups are nested or many examples are checked.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
